# Generated by Django 3.1.1 on 2020-09-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demo', '0002_delete_imageupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
    ]
